name: 'Lazy Release Action'
description: 'The easiest way to create releases for Node projects.'
author: 'Chad Adams'
branding:
  icon: 'image'
  color: 'white'

inputs:
  github-token:
    description: "GitHub Token"
    required: true
  npm-token:
    description: "NPM Token"
    required: false
  snapshots:
    description: "Create a snapshot release"
    required: false
  default-branch:
    description: "Default branch to use for the release"
    required: false
  end-commit:
    description: "The end commit reference."
    required: false
  release-pr-title:
    description: "The title of the release PR"
    required: false

runs:
  using: 'node20'
  main: './dist/index.js'
