name: 'Lazy Release'
description: 'Easily version, publish and create changelogs for your JavaScript/TypeScript projects'
author: 'StellaSoft'
branding:
  icon: 'tag'
  color: 'white'

inputs:
  github-token:
    description: "GitHub Token"
    required: true
  npm-token:
    description: "NPM Token"
    required: false
  snapshots:
    description: "Create a snapshot release"
    required: false
  default-branch:
    description: "Default branch to use for the release"
    required: false
  end-commit:
    description: "The end commit reference."
    required: false
  release-pr-title:
    description: "The title of the release PR"
    required: false
  republish-major-tag:
    description: "Republish the major tag"
    required: false

runs:
  using: 'node20'
  main: './dist/index.js'
