name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Release PR or Release
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        publish-major-tag: true
